2023-10-18 01:50:47 : DEBUG : <module> : 439 : --- Start ---
2023-10-18 01:50:47 : DEBUG : load_ui : 405 : - Load UI -
2023-10-18 01:50:47 : ERROR : <module> : 447 : Failed
2023-10-18 01:50:47 : ERROR : <module> : 448 : No section: 'tkinter'
Traceback (most recent call last):
  File "D:\Documents\GitHub\application\date_time_picker.py", line 444, in <module>
    load_ui()
  File "D:\Documents\GitHub\application\date_time_picker.py", line 410, in load_ui
    ROOT.title(CONFIG.get('tkinter', 'title'))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 782, in get
    d = self._unify_values(section, vars)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 1153, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'tkinter'
2023-10-18 01:50:47 : DEBUG : <module> : 451 : --- End ---
2023-10-18 01:56:47 : DEBUG : <module> : 441 : --- Start ---
2023-10-18 01:56:47 : DEBUG : load_ui : 407 : - Load UI -
2023-10-18 01:56:47 : ERROR : <module> : 449 : Failed
2023-10-18 01:56:47 : ERROR : <module> : 450 : No section: 'tkinter'
Traceback (most recent call last):
  File "D:\Documents\GitHub\application\date_time_picker.py", line 446, in <module>
    load_ui()
  File "D:\Documents\GitHub\application\date_time_picker.py", line 412, in load_ui
    ROOT.title(CONFIG.get('tkinter', 'title'))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 782, in get
    d = self._unify_values(section, vars)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 1153, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'tkinter'
2023-10-18 01:56:47 : DEBUG : <module> : 453 : --- End ---
2023-10-18 13:59:53 : DEBUG : <module> : 441 : --- Start ---
2023-10-18 13:59:53 : DEBUG : load_ui : 407 : - Load UI -
2023-10-18 13:59:53 : ERROR : <module> : 449 : Failed
2023-10-18 13:59:53 : ERROR : <module> : 450 : No section: 'tkinter'
Traceback (most recent call last):
  File "D:\Documents\GitHub\application\date_time_picker.py", line 446, in <module>
    load_ui()
  File "D:\Documents\GitHub\application\date_time_picker.py", line 412, in load_ui
    ROOT.title(CONFIG.get('tkinter', 'title'))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 782, in get
    d = self._unify_values(section, vars)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 1153, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'tkinter'
2023-10-18 13:59:53 : DEBUG : <module> : 453 : --- End ---
2023-10-18 14:00:37 : DEBUG : <module> : 441 : --- Start ---
2023-10-18 14:00:37 : DEBUG : load_ui : 407 : - Load UI -
2023-10-18 14:00:37 : ERROR : <module> : 449 : Failed
2023-10-18 14:00:37 : ERROR : <module> : 450 : No section: 'tkinter'
Traceback (most recent call last):
  File "D:\Documents\GitHub\application\date_time_picker.py", line 446, in <module>
    load_ui()
  File "D:\Documents\GitHub\application\date_time_picker.py", line 412, in load_ui
    ROOT.title(CONFIG.get('tkinter', 'title'))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 782, in get
    d = self._unify_values(section, vars)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 1153, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'tkinter'
2023-10-18 14:00:37 : DEBUG : <module> : 453 : --- End ---
2023-10-18 14:21:51 : DEBUG : <module> : 441 : --- Start ---
2023-10-18 14:21:51 : DEBUG : load_ui : 407 : - Load UI -
2023-10-18 14:21:51 : ERROR : <module> : 449 : Failed
2023-10-18 14:21:51 : ERROR : <module> : 450 : No section: 'tkinter'
Traceback (most recent call last):
  File "D:\Documents\GitHub\application\date_time_picker.py", line 446, in <module>
    load_ui()
  File "D:\Documents\GitHub\application\date_time_picker.py", line 412, in load_ui
    ROOT.title(CONFIG.get('tkinter', 'title'))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 782, in get
    d = self._unify_values(section, vars)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 1153, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'tkinter'
2023-10-18 14:21:51 : DEBUG : <module> : 453 : --- End ---
2023-10-18 14:36:11 : DEBUG : <module> : 441 : --- Start ---
2023-10-18 14:36:11 : DEBUG : load_ui : 407 : - Load UI -
2023-10-18 14:36:11 : ERROR : <module> : 449 : Failed
2023-10-18 14:36:11 : ERROR : <module> : 450 : No section: 'tkinter'
Traceback (most recent call last):
  File "D:\Documents\GitHub\application\date_time_picker.py", line 446, in <module>
    load_ui()
  File "D:\Documents\GitHub\application\date_time_picker.py", line 412, in load_ui
    ROOT.title(CONFIG.get('tkinter', 'title'))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 782, in get
    d = self._unify_values(section, vars)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 1153, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'tkinter'
2023-10-18 14:36:11 : DEBUG : <module> : 453 : --- End ---
